apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort:   {{ .Values.service.externalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ .Values.app }}