kind:       Deployment
apiVersion: extensions/v1beta1
metadata:
  name: got-svc
  labels:
    app: got-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: got-svc
    spec:
      containers:
        - name:  got-svc
          image: quay.io/derailed/got:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name:          api
          env:
          - name:  GOT_DB_NAME
            value: got
          - name:  PORT
            value: "4000"
          - name:  GOT_DB_USER
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  db-user
          - name:  GOT_DB_PWD
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  db-pwd
          - name:  GOT_DB_HOST
            value: got-postgresql
          - name:  GOT_DB_PORT
            value: "5432"
          - name:  SECRET_KEYBASE
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  phx-key